import type { Labels } from "./ModuleEditor.client";

/**
 * Build the ModuleEditor's translated label bag. Kept next to ModuleEditor (which owns the
 * {@link Labels} shape) so the two stay in step, and out of ForgeEntryDetail — whose render path
 * was dominated by this ~85-line literal. `t` is react-i18next's translation function; every key
 * here resolves to a plain string.
 */
export function buildEditorLabels(t: (key: string) => string): Labels {
  return {
    edit: t("editor.edit"),
    save: t("editor.save"),
    saving: t("editor.saving"),
    cancel: t("editor.cancel"),
    saved: t("editor.saved"),
    error: t("editor.error"),
    discardPrompt: t("editor.discardPrompt"),
    discard: t("editor.discard"),
    keepEditing: t("editor.keepEditing"),
    title: t("editor.title"),
    description: t("editor.description"),
    howToInstall: t("editor.howToInstall"),
    faq: t("editor.faq"),
    license: t("editor.license"),
    authorEmail: t("editor.authorEmail"),
    authorURL: t("editor.authorURL"),
    codeRepository: t("editor.codeRepository"),
    authorDisplay: t("editor.authorDisplay"),
    authorDisplayOptions: {
      username: t("editor.authorDisplayOptions.username"),
      fullName: t("editor.authorDisplayOptions.fullName"),
      organisation: t("editor.authorDisplayOptions.organisation"),
    },
    tabGeneral: t("editor.tabGeneral"),
    tabDescription: t("editor.tabDescription"),
    tabInstall: t("editor.tabInstall"),
    tabLicense: t("editor.tabLicense"),
    tabAuthor: t("editor.tabAuthor"),
    tabMedia: t("editor.tabMedia"),
    tablist: t("editor.tablist"),
    loading: t("editor.loading"),
    screenshotsHeading: t("editor.screenshotsHeading"),
    mediaImmediateNote: t("editor.mediaImmediateNote"),
    screenshots: {
      empty: t("screenshots.empty"),
      add: t("screenshots.add"),
      uploading: t("screenshots.uploading"),
      tooLarge: t("screenshots.tooLarge"),
      invalidType: t("screenshots.invalidType"),
      moveUp: t("screenshots.moveUp"),
      moveDown: t("screenshots.moveDown"),
      delete: t("screenshots.delete"),
      confirmPrompt: t("screenshots.confirmPrompt"),
      confirm: t("screenshots.confirm"),
      cancel: t("screenshots.cancel"),
      error: t("screenshots.error"),
    },
    video: {
      heading: t("editor.video.heading"),
      provider: t("editor.video.provider"),
      providerNone: t("editor.video.providerNone"),
      providerYoutube: t("editor.video.providerYoutube"),
      providerVimeo: t("editor.video.providerVimeo"),
      identifier: t("editor.video.identifier"),
      identifierHelp: t("editor.video.identifierHelp"),
      save: t("editor.video.save"),
      saving: t("editor.video.saving"),
      saved: t("editor.video.saved"),
      invalidId: t("editor.video.invalidId"),
      error: t("editor.video.error"),
    },
    icon: {
      label: t("editor.icon.label"),
      choose: t("editor.icon.choose"),
      upload: t("editor.icon.upload"),
      uploading: t("editor.icon.uploading"),
      uploaded: t("editor.icon.uploaded"),
      error: t("editor.icon.error"),
      current: t("editor.icon.current"),
      none: t("editor.icon.none"),
      tooLarge: t("editor.icon.tooLarge"),
      invalidType: t("editor.icon.invalidType"),
    },
    metadata: {
      status: t("editor.metadata.status"),
      category: t("editor.metadata.category"),
      noCategories: t("editor.metadata.noCategories"),
      tags: t("editor.metadata.tags"),
      tag: {
        add: t("editor.metadata.tag.add"),
        remove: t("editor.metadata.tag.remove"),
        placeholder: t("editor.metadata.tag.placeholder"),
      },
    },
  };
}
